version: '3.6'
services:
  php:
    build:
      context: ./docker/php-fpm
      args:
        PHP_EXTENSIONS: "${PHP_EXTENSIONS}"
        PHP_DEPENDENCIES: "${PHP_DEPENDENCIES}"
        UID: "${UID}"
        GID: "${GID}"
    volumes:
      - "./conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./data:/data"

  nginx:
    build:
      context: ./docker/nginx
      args:
        UID: "${UID}"
        GID: "${GID}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./conf/nginx/conf.d:/etc/nginx/conf.d"
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./data:/data"
    environment:
      VIRTUAL_HOST: "${DOMAIN}"

  database:
    image: mysql
    volumes:
      - "./.docker-volumes/database:/var/lib/mysql"
    ports:
      - "3306:3306"
    env_file:
      - .env
