#!/bin/bash
#
# Docker Compose alias commands so we never
# have to manage multiple -f's (As we can just add them to the global)
#

main() {
    $COMPOSE_COMMAND start
}

compose() {
    $COMPOSE_COMMAND $@
}

# usage docker ssh {container}
ssh() {
    $COMPOSE_COMMAND exec --user $USER_ID:$GROUP_ID $1 /bin/bash
}

ps() {
    compose ps $@
}

up() {
    compose up $@
}

down() {
    compose down $@
}

stop() {
    compose stop $@
}

start() {
    compose start $@
}

restart() {
    compose restart $@
}