#!/bin/bash

main() {
    create_env
    assert_file_exists $ENV_FILE
    export ENV_FILE
    build_containers
}

# Read each line of $DEFAULT_ENV_FILE and prompt the user for a value
create_env() {
    if [[ ! -f $ENV_FILE ]]; then
        info "Creating .env file from template. Please enter variables when prompted."
        local vars=()
        while IFS='' read -r line || [[ -n "$line" ]]; do
            vars+=($line)
        done < "$DEFAULT_ENV_FILE"

        # Todo: Fix UID: readonly variable error
        for var in "${vars[@]}"
        do
            read -p "${var}: " ${var}
            echo "${var}=${!var}" >> $ENV_FILE
        done
    else
        info ".env file already exists skipping creation."
    fi
}

build_containers() {
    info "Building docker containers..."
    docker-compose -f ${DOCKER_COMPOSE_FILE} build
    info "Container build complete!"
}